"""change it

Revision ID: 3538b0e9f3b8
Revises: 4c237a328b2f
Create Date: 2026-02-05 17:07:48.379597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3538b0e9f3b8'
down_revision: Union[str, Sequence[str], None] = '4c237a328b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_store_mapping', sa.Column('max_daily_quantity', sa.Integer(), nullable=True))
    op.add_column('product_store_mapping', sa.Column('current_available', sa.Integer(), nullable=True))
    
    # Add column as nullable first with a default value
    op.add_column('purchase_list_items', sa.Column('quantity_to_purchase', sa.Integer(), nullable=True))
    
    # Update existing rows to have default value of 1
    op.execute('UPDATE purchase_list_items SET quantity_to_purchase = 1 WHERE quantity_to_purchase IS NULL')
    
    # Now alter column to be NOT NULL
    op.alter_column('purchase_list_items', 'quantity_to_purchase', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_list_items', 'quantity_to_purchase')
    op.drop_column('product_store_mapping', 'current_available')
    op.drop_column('product_store_mapping', 'max_daily_quantity')
    # ### end Alembic commands ###
