"""Add Holiday model

Revision ID: 4c237a328b2f
Revises: 8f2bbbca7b19
Create Date: 2026-01-05 18:12:23.927505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c237a328b2f'
down_revision: Union[str, Sequence[str], None] = '8f2bbbca7b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('holiday_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('holiday_name', sa.String(length=100), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('holiday_id'),
    sa.UniqueConstraint('holiday_date')
    )
    op.create_index('idx_holiday_date', 'holidays', ['holiday_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_holiday_date', table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
