"""init

Revision ID: 8f2bbbca7b19
Revises: 
Create Date: 2025-12-21 20:26:40.080276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2bbbca7b19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rules',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.Enum('CUTOFF', 'ASSIGNMENT', 'ROUTING', 'PRIORITY', 'CAPACITY', name='ruletype'), nullable=False),
    sa.Column('rule_config', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('cutoff_schedules',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('cutoff_time', sa.Time(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('holiday_override', sa.Boolean(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_in_order_id', sa.String(length=100), nullable=True),
    sa.Column('mall_name', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'PROCESSING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('cutoff_time', sa.DateTime(), nullable=True),
    sa.Column('target_purchase_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('robot_in_order_id')
    )
    op.create_index('idx_order_date', 'orders', ['order_date'], unique=False)
    op.create_index('idx_order_status', 'orders', ['order_status'], unique=False)
    op.create_index('idx_target_purchase_date', 'orders', ['target_purchase_date'], unique=False)
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('staff_code', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('BUYER', 'SUPERVISOR', 'ADMIN', name='staffrole'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EN_ROUTE', 'IDLE', 'OFF_DUTY', name='staffstatus'), nullable=True),
    sa.Column('start_location_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('start_location_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('start_location_name', sa.String(length=200), nullable=True),
    sa.Column('current_location_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('current_location_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('current_location_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_daily_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('staff_code')
    )
    op.create_index('idx_staff_active', 'staff', ['is_active'], unique=False)
    op.create_index('idx_staff_status', 'staff', ['status'], unique=False)
    op.create_table('stores',
    sa.Column('store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('store_code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('store_code')
    )
    op.create_index('idx_store_active', 'stores', ['is_active'], unique=False)
    op.create_index('idx_store_category', 'stores', ['category'], unique=False)
    op.create_index('idx_store_district', 'stores', ['district'], unique=False)
    op.create_table('system_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_type', sa.Enum('INFO', 'WARNING', 'ERROR', 'AUDIT', name='logtype'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_log_created', 'system_logs', ['created_at'], unique=False)
    op.create_index('idx_log_type', 'system_logs', ['log_type'], unique=False)
    op.create_table('order_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_bundle', sa.Boolean(), nullable=True),
    sa.Column('parent_item_id', sa.Integer(), nullable=True),
    sa.Column('item_status', sa.Enum('PENDING', 'ASSIGNED', 'PURCHASED', 'FAILED', 'DISCONTINUED', 'OUT_OF_STOCK', 'RESTOCKING', name='itemstatus'), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_item_id'], ['order_items.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_item_sku', 'order_items', ['sku'], unique=False)
    op.create_index('idx_item_status', 'order_items', ['item_status'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_set_product', sa.Boolean(), nullable=True),
    sa.Column('set_split_rule', sa.JSON(), nullable=True),
    sa.Column('is_store_fixed', sa.Boolean(), nullable=True),
    sa.Column('fixed_store_id', sa.Integer(), nullable=True),
    sa.Column('exclude_from_routing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixed_store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_product_category', 'products', ['category'], unique=False)
    op.create_table('purchase_lists',
    sa.Column('list_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('list_status', sa.Enum('DRAFT', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', name='liststatus'), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_stores', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('list_id')
    )
    op.create_index('idx_list_status', 'purchase_lists', ['list_status'], unique=False)
    op.create_index('idx_purchase_date', 'purchase_lists', ['purchase_date'], unique=False)
    op.create_table('store_distance_matrix',
    sa.Column('matrix_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_store_id', sa.Integer(), nullable=False),
    sa.Column('to_store_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('travel_time_minutes', sa.Integer(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('matrix_id'),
    sa.UniqueConstraint('from_store_id', 'to_store_id', name='uq_store_distance')
    )
    op.create_index('idx_distance_from_store', 'store_distance_matrix', ['from_store_id'], unique=False)
    op.create_table('product_store_mapping',
    sa.Column('mapping_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('is_primary_store', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('last_available_date', sa.Date(), nullable=True),
    sa.Column('stock_status', sa.Enum('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'DISCONTINUED', 'UNKNOWN', name='stockstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mapping_id'),
    sa.UniqueConstraint('product_id', 'store_id', name='uq_product_store')
    )
    op.create_index('idx_mapping_stock_status', 'product_store_mapping', ['stock_status'], unique=False)
    op.create_table('purchase_list_items',
    sa.Column('list_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('purchase_status', sa.Enum('PENDING', 'IN_PROGRESS', 'PURCHASED', 'FAILED', 'SKIPPED', name='purchasestatus'), nullable=True),
    sa.Column('actual_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_time', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['order_items.item_id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['purchase_lists.list_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('list_item_id')
    )
    op.create_index('idx_purchase_status', 'purchase_list_items', ['purchase_status'], unique=False)
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('route_date', sa.Date(), nullable=False),
    sa.Column('start_location_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('start_location_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('total_distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('route_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='routestatus'), nullable=True),
    sa.Column('include_return', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['purchase_lists.list_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index('idx_route_date', 'routes', ['route_date'], unique=False)
    op.create_index('idx_route_status', 'routes', ['route_status'], unique=False)
    op.create_table('store_inventory',
    sa.Column('inventory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock_status', sa.Enum('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'DISCONTINUED', 'UNKNOWN', name='stockstatus'), nullable=True),
    sa.Column('discontinuation_date', sa.Date(), nullable=True),
    sa.Column('expected_restock_date', sa.Date(), nullable=True),
    sa.Column('last_checked_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('store_id', 'product_id', name='uq_store_product_inventory')
    )
    op.create_table('purchase_failures',
    sa.Column('failure_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_item_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('failure_type', sa.Enum('DISCONTINUED', 'OUT_OF_STOCK', 'STORE_CLOSED', 'PRICE_MISMATCH', 'PRODUCT_NOT_FOUND', 'OTHER', name='failuretype'), nullable=False),
    sa.Column('failure_date', sa.DateTime(), nullable=True),
    sa.Column('expected_restock_date', sa.Date(), nullable=True),
    sa.Column('alternative_store_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alternative_store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['order_items.item_id'], ),
    sa.ForeignKeyConstraint(['list_item_id'], ['purchase_list_items.list_item_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('failure_id')
    )
    op.create_index('idx_failure_date', 'purchase_failures', ['failure_date'], unique=False)
    op.create_index('idx_failure_type', 'purchase_failures', ['failure_type'], unique=False)
    op.create_table('route_stops',
    sa.Column('stop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.Column('items_to_purchase', sa.JSON(), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=True),
    sa.Column('stop_status', sa.Enum('PENDING', 'CURRENT', 'COMPLETED', 'SKIPPED', name='stopstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_index('idx_stop_sequence', 'route_stops', ['route_id', 'stop_sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stop_sequence', table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index('idx_failure_type', table_name='purchase_failures')
    op.drop_index('idx_failure_date', table_name='purchase_failures')
    op.drop_table('purchase_failures')
    op.drop_table('store_inventory')
    op.drop_index('idx_route_status', table_name='routes')
    op.drop_index('idx_route_date', table_name='routes')
    op.drop_table('routes')
    op.drop_index('idx_purchase_status', table_name='purchase_list_items')
    op.drop_table('purchase_list_items')
    op.drop_index('idx_mapping_stock_status', table_name='product_store_mapping')
    op.drop_table('product_store_mapping')
    op.drop_index('idx_distance_from_store', table_name='store_distance_matrix')
    op.drop_table('store_distance_matrix')
    op.drop_index('idx_purchase_date', table_name='purchase_lists')
    op.drop_index('idx_list_status', table_name='purchase_lists')
    op.drop_table('purchase_lists')
    op.drop_index('idx_product_category', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_item_status', table_name='order_items')
    op.drop_index('idx_item_sku', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_log_type', table_name='system_logs')
    op.drop_index('idx_log_created', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('idx_store_district', table_name='stores')
    op.drop_index('idx_store_category', table_name='stores')
    op.drop_index('idx_store_active', table_name='stores')
    op.drop_table('stores')
    op.drop_index('idx_staff_status', table_name='staff')
    op.drop_index('idx_staff_active', table_name='staff')
    op.drop_table('staff')
    op.drop_index('idx_target_purchase_date', table_name='orders')
    op.drop_index('idx_order_status', table_name='orders')
    op.drop_index('idx_order_date', table_name='orders')
    op.drop_table('orders')
    op.drop_table('cutoff_schedules')
    op.drop_table('business_rules')
    # ### end Alembic commands ###
